### ISSUE TITLE
fix 1 bug

### ISSUE THREAD

**Issue by did999** [pyreadline3/pyreadline3#25]
when i use python with terminal：
```
>>> exit()
Exception ignored in atexit callback: <function enablerlcompleter.<locals>.register_readline.<locals>.write_history at 0x000001900301D580>
Traceback (most recent call last):
  File "<frozen site>", line 482, in write_history
  File "C:\Users\vgabr\.conda\envs\comfyui\Lib\site-packages\pyreadline3\rlmain.py", line 183, in write_history_file
    self.mode._history.write_history_file(filename)
  File "C:\Users\vgabr\.conda\envs\comfyui\Lib\site-packages\pyreadline3\lineeditor\history.py", line 105, in write_history_file
    fp.writeln(line.get_line_text())
    ^^^^^^^^^^
AttributeError: '_io.TextIOWrapper' object has no attribute 'writeln'
```

so locate line 105：
change `fp.writeln(line.get_line_text())` >`fp.write(line.get_line_text() + '\n')`

**Comment by jmw182** [comment]
@did999 can you please re-open this issue since it has not been fixed yet in the actual package? 

I can confirm that the fixes that @did999 and @chrislast propose work for me. Can this line be fixed for the next release?
